### ISSUE TITLE
Supported validator list is outdated

### ISSUE THREAD

**Issue by kenhys** [redpen-cc/redpen-doc#16]
There are outdated validators in source/validator.rst:
```
- SpaceAfterPeriod
#=> SpaceBeginningOfSentence
- SpaceWithSymbol
#=> SymbolWithSpace
```

**Comment by takahi-i** [comment]
Thank you a lot for the report @kenhys!  I will look into the section.

**Comment by takahi-i** [comment]
Oops I closed this issue mistakenly..  I confirmed that the names of validators are outdate as you describe and change the names.
