### ISSUE TITLE
AsciiDoctor style setting

### ISSUE THREAD

**Issue by takahi-i** [redpen-cc/redpen-doc#25]
Current the RedPen document uses the default style setting by AsciiDoctor. I think this style is good enough but feel need RedPen original one.

**Comment by taky** [comment]
OK, I'll take this issue ;)

**Comment by takahi-i** [comment]
Thanks!

**Comment by taky** [comment]
You're welcome ;)

**Comment by takahi-i** [comment]
Excellent @taky!  Closed with #26.
