### ISSUE TITLE
VERTICAL_BAR Spelling mistake

### ISSUE THREAD

**Issue by ABCanG** [redpen-cc/redpen-doc#44]
Hello,
In this document, a vertical bar is explained `VERTICAL_VAR`
But it seems correct that it is `VERTICAL_BAR`.
Thank you.

https://github.com/redpen-cc/redpen-doc/blob/master/source/configuration.adoc

**Comment by takahi-i** [comment]
Thank you very much for the valuable comment @ABCanG! I will fix this.

**Comment by takahi-i** [comment]
Hello @ABCanG I fixed the spelling mistake in #45.
