### ISSUE TITLE
Wrong validator name: "StartWithCapitalLetterValidator" -> "StartWithCapitalLetter"

### ISSUE THREAD

**Issue by shuntaroy** [redpen-cc/redpen-doc#89]
I noticed this because linter-redpen on Atom causes an error and stops when I use this validator as it written in this doc ("StartWithCapitalLetterValidator").
And I happen to find its correct name was "StartWithCapitalLetter".

**Comment by takahi-i** [comment]
Hello @shuntaroy, Thank you very much for the valuable report. I will fix the document immediately.

**Comment by takahi-i** [comment]
I fixed the mistakes in the manual. Thanks!
